### ISSUE TITLE
"set-output" is getting deprecated

### ISSUE THREAD

**Issue by MariusVB** [jsdaniell/create-json#3]
I think that this action is the culprit of some recent warnings I'm getting in my action logs. More specifically this error:

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

You can read about how to change it [here](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).

Only the compiled code is available in your repo, but if you share the Typescript I can help change it if needed.

https://github.com/jsdaniell/create-json/blob/c341fa94e0f0bcbc1eca51f2b8da61084e03dfff/dist/index.js#L273

**Comment by TroniPM** [comment]
@MariusVB you can fork and change the `package.json` to:
```    
    "@actions/core": "^1.10.0",
    "@actions/github": "^4.0.0",
```

Than call the action by your username/create-json@master:

I don't know if this will break <16 node versions, but this worked fine to me.

**Comment by jsdaniell** [comment]
I will work on a new version with this fix, but until now follow the @TroniPM workaround.

**Comment by MariusVB** [comment]
> @MariusVB you can fork and change the `package.json` to:

I would rather not have to create an unmaintained fork, just to get rid of a warning. Will wait for new version.
