### ISSUE TITLE
Update set-output use

### ISSUE THREAD

**Issue by coolusaHD** [jsdaniell/create-json#6]
I get the warning `Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

**Comment by ZeRego** [comment]
> Action authors who are using the toolkit should update the @actions/core package to v1.10.0 or greater to get the updated saveState and setOutput functions.

package.json seems to have the correct version:

https://github.com/jsdaniell/create-json/blob/master/package.json#L26

package-lock.json mentions a `"@actions/core": "^1.2.3"` which could be the problem:

https://github.com/jsdaniell/create-json/blob/master/package-lock.json#L12

**Comment by coolusaHD** [comment]
I'm now using https://github.com/andrew-fennell/create-env-json as alternative
