### ISSUE TITLE
Node.js 16 actions are deprecated

### ISSUE THREAD

**Issue by andokai** [jsdaniell/create-json#7]
Hi, it seems this package is using node 16 which is now deprecated. I guess the `runs` block needs to be updated.

`Please update the following actions to use Node.js 20: jsdaniell/create-json@v1.2.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by StaziaPhoenix** [comment]
I noticed this this morning too! +1 on the ask

**Comment by manuelpagliuca** [comment]
I noticed the same yesterday morning, we probably need a new version.

**Comment by MurilloCunha** [comment]
I opened this PR https://github.com/jsdaniell/create-json/pull/8 , i think this can solve the problem

**Comment by jsdaniell** [comment]
Merged the update, next days I will update the docs to the new release, thank you for the PR @MurilloCunha
